/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package baconhep;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TTau extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TTau\",\"namespace\":\"baconhep\",\"fields\":[{\"name\":\"pt\",\"type\":\"float\"},{\"name\":\"eta\",\"type\":\"float\"},{\"name\":\"phi\",\"type\":\"float\"},{\"name\":\"m\",\"type\":\"float\"},{\"name\":\"e\",\"type\":\"float\"},{\"name\":\"q\",\"type\":\"int\"},{\"name\":\"dzLeadChHad\",\"type\":\"float\"},{\"name\":\"nSignalChHad\",\"type\":\"long\"},{\"name\":\"nSignalGamma\",\"type\":\"long\"},{\"name\":\"antiEleMVA5\",\"type\":\"float\"},{\"name\":\"antiEleMVA5Cat\",\"type\":\"float\"},{\"name\":\"rawMuonRejection\",\"type\":\"float\"},{\"name\":\"rawIso3Hits\",\"type\":\"float\"},{\"name\":\"rawIsoMVA3oldDMwoLT\",\"type\":\"float\"},{\"name\":\"rawIsoMVA3oldDMwLT\",\"type\":\"float\"},{\"name\":\"rawIsoMVA3newDMwoLT\",\"type\":\"float\"},{\"name\":\"rawIsoMVA3newDMwLT\",\"type\":\"float\"},{\"name\":\"puppiChHadIso\",\"type\":\"float\"},{\"name\":\"puppiGammaIso\",\"type\":\"float\"},{\"name\":\"puppiNeuHadIso\",\"type\":\"float\"},{\"name\":\"puppiChHadIsoNoLep\",\"type\":\"float\"},{\"name\":\"puppiGammaIsoNoLep\",\"type\":\"float\"},{\"name\":\"puppiNeuHadIsoNoLep\",\"type\":\"float\"},{\"name\":\"hpsDisc\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public float pt;
  @Deprecated public float eta;
  @Deprecated public float phi;
  @Deprecated public float m;
  @Deprecated public float e;
  @Deprecated public int q;
  @Deprecated public float dzLeadChHad;
  @Deprecated public long nSignalChHad;
  @Deprecated public long nSignalGamma;
  @Deprecated public float antiEleMVA5;
  @Deprecated public float antiEleMVA5Cat;
  @Deprecated public float rawMuonRejection;
  @Deprecated public float rawIso3Hits;
  @Deprecated public float rawIsoMVA3oldDMwoLT;
  @Deprecated public float rawIsoMVA3oldDMwLT;
  @Deprecated public float rawIsoMVA3newDMwoLT;
  @Deprecated public float rawIsoMVA3newDMwLT;
  @Deprecated public float puppiChHadIso;
  @Deprecated public float puppiGammaIso;
  @Deprecated public float puppiNeuHadIso;
  @Deprecated public float puppiChHadIsoNoLep;
  @Deprecated public float puppiGammaIsoNoLep;
  @Deprecated public float puppiNeuHadIsoNoLep;
  @Deprecated public double hpsDisc;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TTau() {}

  /**
   * All-args constructor.
   */
  public TTau(java.lang.Float pt, java.lang.Float eta, java.lang.Float phi, java.lang.Float m, java.lang.Float e, java.lang.Integer q, java.lang.Float dzLeadChHad, java.lang.Long nSignalChHad, java.lang.Long nSignalGamma, java.lang.Float antiEleMVA5, java.lang.Float antiEleMVA5Cat, java.lang.Float rawMuonRejection, java.lang.Float rawIso3Hits, java.lang.Float rawIsoMVA3oldDMwoLT, java.lang.Float rawIsoMVA3oldDMwLT, java.lang.Float rawIsoMVA3newDMwoLT, java.lang.Float rawIsoMVA3newDMwLT, java.lang.Float puppiChHadIso, java.lang.Float puppiGammaIso, java.lang.Float puppiNeuHadIso, java.lang.Float puppiChHadIsoNoLep, java.lang.Float puppiGammaIsoNoLep, java.lang.Float puppiNeuHadIsoNoLep, java.lang.Double hpsDisc) {
    this.pt = pt;
    this.eta = eta;
    this.phi = phi;
    this.m = m;
    this.e = e;
    this.q = q;
    this.dzLeadChHad = dzLeadChHad;
    this.nSignalChHad = nSignalChHad;
    this.nSignalGamma = nSignalGamma;
    this.antiEleMVA5 = antiEleMVA5;
    this.antiEleMVA5Cat = antiEleMVA5Cat;
    this.rawMuonRejection = rawMuonRejection;
    this.rawIso3Hits = rawIso3Hits;
    this.rawIsoMVA3oldDMwoLT = rawIsoMVA3oldDMwoLT;
    this.rawIsoMVA3oldDMwLT = rawIsoMVA3oldDMwLT;
    this.rawIsoMVA3newDMwoLT = rawIsoMVA3newDMwoLT;
    this.rawIsoMVA3newDMwLT = rawIsoMVA3newDMwLT;
    this.puppiChHadIso = puppiChHadIso;
    this.puppiGammaIso = puppiGammaIso;
    this.puppiNeuHadIso = puppiNeuHadIso;
    this.puppiChHadIsoNoLep = puppiChHadIsoNoLep;
    this.puppiGammaIsoNoLep = puppiGammaIsoNoLep;
    this.puppiNeuHadIsoNoLep = puppiNeuHadIsoNoLep;
    this.hpsDisc = hpsDisc;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return pt;
    case 1: return eta;
    case 2: return phi;
    case 3: return m;
    case 4: return e;
    case 5: return q;
    case 6: return dzLeadChHad;
    case 7: return nSignalChHad;
    case 8: return nSignalGamma;
    case 9: return antiEleMVA5;
    case 10: return antiEleMVA5Cat;
    case 11: return rawMuonRejection;
    case 12: return rawIso3Hits;
    case 13: return rawIsoMVA3oldDMwoLT;
    case 14: return rawIsoMVA3oldDMwLT;
    case 15: return rawIsoMVA3newDMwoLT;
    case 16: return rawIsoMVA3newDMwLT;
    case 17: return puppiChHadIso;
    case 18: return puppiGammaIso;
    case 19: return puppiNeuHadIso;
    case 20: return puppiChHadIsoNoLep;
    case 21: return puppiGammaIsoNoLep;
    case 22: return puppiNeuHadIsoNoLep;
    case 23: return hpsDisc;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: pt = (java.lang.Float)value$; break;
    case 1: eta = (java.lang.Float)value$; break;
    case 2: phi = (java.lang.Float)value$; break;
    case 3: m = (java.lang.Float)value$; break;
    case 4: e = (java.lang.Float)value$; break;
    case 5: q = (java.lang.Integer)value$; break;
    case 6: dzLeadChHad = (java.lang.Float)value$; break;
    case 7: nSignalChHad = (java.lang.Long)value$; break;
    case 8: nSignalGamma = (java.lang.Long)value$; break;
    case 9: antiEleMVA5 = (java.lang.Float)value$; break;
    case 10: antiEleMVA5Cat = (java.lang.Float)value$; break;
    case 11: rawMuonRejection = (java.lang.Float)value$; break;
    case 12: rawIso3Hits = (java.lang.Float)value$; break;
    case 13: rawIsoMVA3oldDMwoLT = (java.lang.Float)value$; break;
    case 14: rawIsoMVA3oldDMwLT = (java.lang.Float)value$; break;
    case 15: rawIsoMVA3newDMwoLT = (java.lang.Float)value$; break;
    case 16: rawIsoMVA3newDMwLT = (java.lang.Float)value$; break;
    case 17: puppiChHadIso = (java.lang.Float)value$; break;
    case 18: puppiGammaIso = (java.lang.Float)value$; break;
    case 19: puppiNeuHadIso = (java.lang.Float)value$; break;
    case 20: puppiChHadIsoNoLep = (java.lang.Float)value$; break;
    case 21: puppiGammaIsoNoLep = (java.lang.Float)value$; break;
    case 22: puppiNeuHadIsoNoLep = (java.lang.Float)value$; break;
    case 23: hpsDisc = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'pt' field.
   */
  public java.lang.Float getPt() {
    return pt;
  }

  /**
   * Sets the value of the 'pt' field.
   * @param value the value to set.
   */
  public void setPt(java.lang.Float value) {
    this.pt = value;
  }

  /**
   * Gets the value of the 'eta' field.
   */
  public java.lang.Float getEta() {
    return eta;
  }

  /**
   * Sets the value of the 'eta' field.
   * @param value the value to set.
   */
  public void setEta(java.lang.Float value) {
    this.eta = value;
  }

  /**
   * Gets the value of the 'phi' field.
   */
  public java.lang.Float getPhi() {
    return phi;
  }

  /**
   * Sets the value of the 'phi' field.
   * @param value the value to set.
   */
  public void setPhi(java.lang.Float value) {
    this.phi = value;
  }

  /**
   * Gets the value of the 'm' field.
   */
  public java.lang.Float getM() {
    return m;
  }

  /**
   * Sets the value of the 'm' field.
   * @param value the value to set.
   */
  public void setM(java.lang.Float value) {
    this.m = value;
  }

  /**
   * Gets the value of the 'e' field.
   */
  public java.lang.Float getE() {
    return e;
  }

  /**
   * Sets the value of the 'e' field.
   * @param value the value to set.
   */
  public void setE(java.lang.Float value) {
    this.e = value;
  }

  /**
   * Gets the value of the 'q' field.
   */
  public java.lang.Integer getQ() {
    return q;
  }

  /**
   * Sets the value of the 'q' field.
   * @param value the value to set.
   */
  public void setQ(java.lang.Integer value) {
    this.q = value;
  }

  /**
   * Gets the value of the 'dzLeadChHad' field.
   */
  public java.lang.Float getDzLeadChHad() {
    return dzLeadChHad;
  }

  /**
   * Sets the value of the 'dzLeadChHad' field.
   * @param value the value to set.
   */
  public void setDzLeadChHad(java.lang.Float value) {
    this.dzLeadChHad = value;
  }

  /**
   * Gets the value of the 'nSignalChHad' field.
   */
  public java.lang.Long getNSignalChHad() {
    return nSignalChHad;
  }

  /**
   * Sets the value of the 'nSignalChHad' field.
   * @param value the value to set.
   */
  public void setNSignalChHad(java.lang.Long value) {
    this.nSignalChHad = value;
  }

  /**
   * Gets the value of the 'nSignalGamma' field.
   */
  public java.lang.Long getNSignalGamma() {
    return nSignalGamma;
  }

  /**
   * Sets the value of the 'nSignalGamma' field.
   * @param value the value to set.
   */
  public void setNSignalGamma(java.lang.Long value) {
    this.nSignalGamma = value;
  }

  /**
   * Gets the value of the 'antiEleMVA5' field.
   */
  public java.lang.Float getAntiEleMVA5() {
    return antiEleMVA5;
  }

  /**
   * Sets the value of the 'antiEleMVA5' field.
   * @param value the value to set.
   */
  public void setAntiEleMVA5(java.lang.Float value) {
    this.antiEleMVA5 = value;
  }

  /**
   * Gets the value of the 'antiEleMVA5Cat' field.
   */
  public java.lang.Float getAntiEleMVA5Cat() {
    return antiEleMVA5Cat;
  }

  /**
   * Sets the value of the 'antiEleMVA5Cat' field.
   * @param value the value to set.
   */
  public void setAntiEleMVA5Cat(java.lang.Float value) {
    this.antiEleMVA5Cat = value;
  }

  /**
   * Gets the value of the 'rawMuonRejection' field.
   */
  public java.lang.Float getRawMuonRejection() {
    return rawMuonRejection;
  }

  /**
   * Sets the value of the 'rawMuonRejection' field.
   * @param value the value to set.
   */
  public void setRawMuonRejection(java.lang.Float value) {
    this.rawMuonRejection = value;
  }

  /**
   * Gets the value of the 'rawIso3Hits' field.
   */
  public java.lang.Float getRawIso3Hits() {
    return rawIso3Hits;
  }

  /**
   * Sets the value of the 'rawIso3Hits' field.
   * @param value the value to set.
   */
  public void setRawIso3Hits(java.lang.Float value) {
    this.rawIso3Hits = value;
  }

  /**
   * Gets the value of the 'rawIsoMVA3oldDMwoLT' field.
   */
  public java.lang.Float getRawIsoMVA3oldDMwoLT() {
    return rawIsoMVA3oldDMwoLT;
  }

  /**
   * Sets the value of the 'rawIsoMVA3oldDMwoLT' field.
   * @param value the value to set.
   */
  public void setRawIsoMVA3oldDMwoLT(java.lang.Float value) {
    this.rawIsoMVA3oldDMwoLT = value;
  }

  /**
   * Gets the value of the 'rawIsoMVA3oldDMwLT' field.
   */
  public java.lang.Float getRawIsoMVA3oldDMwLT() {
    return rawIsoMVA3oldDMwLT;
  }

  /**
   * Sets the value of the 'rawIsoMVA3oldDMwLT' field.
   * @param value the value to set.
   */
  public void setRawIsoMVA3oldDMwLT(java.lang.Float value) {
    this.rawIsoMVA3oldDMwLT = value;
  }

  /**
   * Gets the value of the 'rawIsoMVA3newDMwoLT' field.
   */
  public java.lang.Float getRawIsoMVA3newDMwoLT() {
    return rawIsoMVA3newDMwoLT;
  }

  /**
   * Sets the value of the 'rawIsoMVA3newDMwoLT' field.
   * @param value the value to set.
   */
  public void setRawIsoMVA3newDMwoLT(java.lang.Float value) {
    this.rawIsoMVA3newDMwoLT = value;
  }

  /**
   * Gets the value of the 'rawIsoMVA3newDMwLT' field.
   */
  public java.lang.Float getRawIsoMVA3newDMwLT() {
    return rawIsoMVA3newDMwLT;
  }

  /**
   * Sets the value of the 'rawIsoMVA3newDMwLT' field.
   * @param value the value to set.
   */
  public void setRawIsoMVA3newDMwLT(java.lang.Float value) {
    this.rawIsoMVA3newDMwLT = value;
  }

  /**
   * Gets the value of the 'puppiChHadIso' field.
   */
  public java.lang.Float getPuppiChHadIso() {
    return puppiChHadIso;
  }

  /**
   * Sets the value of the 'puppiChHadIso' field.
   * @param value the value to set.
   */
  public void setPuppiChHadIso(java.lang.Float value) {
    this.puppiChHadIso = value;
  }

  /**
   * Gets the value of the 'puppiGammaIso' field.
   */
  public java.lang.Float getPuppiGammaIso() {
    return puppiGammaIso;
  }

  /**
   * Sets the value of the 'puppiGammaIso' field.
   * @param value the value to set.
   */
  public void setPuppiGammaIso(java.lang.Float value) {
    this.puppiGammaIso = value;
  }

  /**
   * Gets the value of the 'puppiNeuHadIso' field.
   */
  public java.lang.Float getPuppiNeuHadIso() {
    return puppiNeuHadIso;
  }

  /**
   * Sets the value of the 'puppiNeuHadIso' field.
   * @param value the value to set.
   */
  public void setPuppiNeuHadIso(java.lang.Float value) {
    this.puppiNeuHadIso = value;
  }

  /**
   * Gets the value of the 'puppiChHadIsoNoLep' field.
   */
  public java.lang.Float getPuppiChHadIsoNoLep() {
    return puppiChHadIsoNoLep;
  }

  /**
   * Sets the value of the 'puppiChHadIsoNoLep' field.
   * @param value the value to set.
   */
  public void setPuppiChHadIsoNoLep(java.lang.Float value) {
    this.puppiChHadIsoNoLep = value;
  }

  /**
   * Gets the value of the 'puppiGammaIsoNoLep' field.
   */
  public java.lang.Float getPuppiGammaIsoNoLep() {
    return puppiGammaIsoNoLep;
  }

  /**
   * Sets the value of the 'puppiGammaIsoNoLep' field.
   * @param value the value to set.
   */
  public void setPuppiGammaIsoNoLep(java.lang.Float value) {
    this.puppiGammaIsoNoLep = value;
  }

  /**
   * Gets the value of the 'puppiNeuHadIsoNoLep' field.
   */
  public java.lang.Float getPuppiNeuHadIsoNoLep() {
    return puppiNeuHadIsoNoLep;
  }

  /**
   * Sets the value of the 'puppiNeuHadIsoNoLep' field.
   * @param value the value to set.
   */
  public void setPuppiNeuHadIsoNoLep(java.lang.Float value) {
    this.puppiNeuHadIsoNoLep = value;
  }

  /**
   * Gets the value of the 'hpsDisc' field.
   */
  public java.lang.Double getHpsDisc() {
    return hpsDisc;
  }

  /**
   * Sets the value of the 'hpsDisc' field.
   * @param value the value to set.
   */
  public void setHpsDisc(java.lang.Double value) {
    this.hpsDisc = value;
  }

  /** Creates a new TTau RecordBuilder */
  public static baconhep.TTau.Builder newBuilder() {
    return new baconhep.TTau.Builder();
  }
  
  /** Creates a new TTau RecordBuilder by copying an existing Builder */
  public static baconhep.TTau.Builder newBuilder(baconhep.TTau.Builder other) {
    return new baconhep.TTau.Builder(other);
  }
  
  /** Creates a new TTau RecordBuilder by copying an existing TTau instance */
  public static baconhep.TTau.Builder newBuilder(baconhep.TTau other) {
    return new baconhep.TTau.Builder(other);
  }
  
  /**
   * RecordBuilder for TTau instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TTau>
    implements org.apache.avro.data.RecordBuilder<TTau> {

    private float pt;
    private float eta;
    private float phi;
    private float m;
    private float e;
    private int q;
    private float dzLeadChHad;
    private long nSignalChHad;
    private long nSignalGamma;
    private float antiEleMVA5;
    private float antiEleMVA5Cat;
    private float rawMuonRejection;
    private float rawIso3Hits;
    private float rawIsoMVA3oldDMwoLT;
    private float rawIsoMVA3oldDMwLT;
    private float rawIsoMVA3newDMwoLT;
    private float rawIsoMVA3newDMwLT;
    private float puppiChHadIso;
    private float puppiGammaIso;
    private float puppiNeuHadIso;
    private float puppiChHadIsoNoLep;
    private float puppiGammaIsoNoLep;
    private float puppiNeuHadIsoNoLep;
    private double hpsDisc;

    /** Creates a new Builder */
    private Builder() {
      super(baconhep.TTau.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(baconhep.TTau.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.pt)) {
        this.pt = data().deepCopy(fields()[0].schema(), other.pt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eta)) {
        this.eta = data().deepCopy(fields()[1].schema(), other.eta);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.phi)) {
        this.phi = data().deepCopy(fields()[2].schema(), other.phi);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.m)) {
        this.m = data().deepCopy(fields()[3].schema(), other.m);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.e)) {
        this.e = data().deepCopy(fields()[4].schema(), other.e);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.q)) {
        this.q = data().deepCopy(fields()[5].schema(), other.q);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dzLeadChHad)) {
        this.dzLeadChHad = data().deepCopy(fields()[6].schema(), other.dzLeadChHad);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.nSignalChHad)) {
        this.nSignalChHad = data().deepCopy(fields()[7].schema(), other.nSignalChHad);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.nSignalGamma)) {
        this.nSignalGamma = data().deepCopy(fields()[8].schema(), other.nSignalGamma);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.antiEleMVA5)) {
        this.antiEleMVA5 = data().deepCopy(fields()[9].schema(), other.antiEleMVA5);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.antiEleMVA5Cat)) {
        this.antiEleMVA5Cat = data().deepCopy(fields()[10].schema(), other.antiEleMVA5Cat);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.rawMuonRejection)) {
        this.rawMuonRejection = data().deepCopy(fields()[11].schema(), other.rawMuonRejection);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.rawIso3Hits)) {
        this.rawIso3Hits = data().deepCopy(fields()[12].schema(), other.rawIso3Hits);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.rawIsoMVA3oldDMwoLT)) {
        this.rawIsoMVA3oldDMwoLT = data().deepCopy(fields()[13].schema(), other.rawIsoMVA3oldDMwoLT);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.rawIsoMVA3oldDMwLT)) {
        this.rawIsoMVA3oldDMwLT = data().deepCopy(fields()[14].schema(), other.rawIsoMVA3oldDMwLT);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.rawIsoMVA3newDMwoLT)) {
        this.rawIsoMVA3newDMwoLT = data().deepCopy(fields()[15].schema(), other.rawIsoMVA3newDMwoLT);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.rawIsoMVA3newDMwLT)) {
        this.rawIsoMVA3newDMwLT = data().deepCopy(fields()[16].schema(), other.rawIsoMVA3newDMwLT);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.puppiChHadIso)) {
        this.puppiChHadIso = data().deepCopy(fields()[17].schema(), other.puppiChHadIso);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.puppiGammaIso)) {
        this.puppiGammaIso = data().deepCopy(fields()[18].schema(), other.puppiGammaIso);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.puppiNeuHadIso)) {
        this.puppiNeuHadIso = data().deepCopy(fields()[19].schema(), other.puppiNeuHadIso);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.puppiChHadIsoNoLep)) {
        this.puppiChHadIsoNoLep = data().deepCopy(fields()[20].schema(), other.puppiChHadIsoNoLep);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.puppiGammaIsoNoLep)) {
        this.puppiGammaIsoNoLep = data().deepCopy(fields()[21].schema(), other.puppiGammaIsoNoLep);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.puppiNeuHadIsoNoLep)) {
        this.puppiNeuHadIsoNoLep = data().deepCopy(fields()[22].schema(), other.puppiNeuHadIsoNoLep);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.hpsDisc)) {
        this.hpsDisc = data().deepCopy(fields()[23].schema(), other.hpsDisc);
        fieldSetFlags()[23] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TTau instance */
    private Builder(baconhep.TTau other) {
            super(baconhep.TTau.SCHEMA$);
      if (isValidValue(fields()[0], other.pt)) {
        this.pt = data().deepCopy(fields()[0].schema(), other.pt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eta)) {
        this.eta = data().deepCopy(fields()[1].schema(), other.eta);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.phi)) {
        this.phi = data().deepCopy(fields()[2].schema(), other.phi);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.m)) {
        this.m = data().deepCopy(fields()[3].schema(), other.m);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.e)) {
        this.e = data().deepCopy(fields()[4].schema(), other.e);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.q)) {
        this.q = data().deepCopy(fields()[5].schema(), other.q);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dzLeadChHad)) {
        this.dzLeadChHad = data().deepCopy(fields()[6].schema(), other.dzLeadChHad);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.nSignalChHad)) {
        this.nSignalChHad = data().deepCopy(fields()[7].schema(), other.nSignalChHad);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.nSignalGamma)) {
        this.nSignalGamma = data().deepCopy(fields()[8].schema(), other.nSignalGamma);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.antiEleMVA5)) {
        this.antiEleMVA5 = data().deepCopy(fields()[9].schema(), other.antiEleMVA5);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.antiEleMVA5Cat)) {
        this.antiEleMVA5Cat = data().deepCopy(fields()[10].schema(), other.antiEleMVA5Cat);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.rawMuonRejection)) {
        this.rawMuonRejection = data().deepCopy(fields()[11].schema(), other.rawMuonRejection);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.rawIso3Hits)) {
        this.rawIso3Hits = data().deepCopy(fields()[12].schema(), other.rawIso3Hits);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.rawIsoMVA3oldDMwoLT)) {
        this.rawIsoMVA3oldDMwoLT = data().deepCopy(fields()[13].schema(), other.rawIsoMVA3oldDMwoLT);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.rawIsoMVA3oldDMwLT)) {
        this.rawIsoMVA3oldDMwLT = data().deepCopy(fields()[14].schema(), other.rawIsoMVA3oldDMwLT);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.rawIsoMVA3newDMwoLT)) {
        this.rawIsoMVA3newDMwoLT = data().deepCopy(fields()[15].schema(), other.rawIsoMVA3newDMwoLT);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.rawIsoMVA3newDMwLT)) {
        this.rawIsoMVA3newDMwLT = data().deepCopy(fields()[16].schema(), other.rawIsoMVA3newDMwLT);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.puppiChHadIso)) {
        this.puppiChHadIso = data().deepCopy(fields()[17].schema(), other.puppiChHadIso);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.puppiGammaIso)) {
        this.puppiGammaIso = data().deepCopy(fields()[18].schema(), other.puppiGammaIso);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.puppiNeuHadIso)) {
        this.puppiNeuHadIso = data().deepCopy(fields()[19].schema(), other.puppiNeuHadIso);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.puppiChHadIsoNoLep)) {
        this.puppiChHadIsoNoLep = data().deepCopy(fields()[20].schema(), other.puppiChHadIsoNoLep);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.puppiGammaIsoNoLep)) {
        this.puppiGammaIsoNoLep = data().deepCopy(fields()[21].schema(), other.puppiGammaIsoNoLep);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.puppiNeuHadIsoNoLep)) {
        this.puppiNeuHadIsoNoLep = data().deepCopy(fields()[22].schema(), other.puppiNeuHadIsoNoLep);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.hpsDisc)) {
        this.hpsDisc = data().deepCopy(fields()[23].schema(), other.hpsDisc);
        fieldSetFlags()[23] = true;
      }
    }

    /** Gets the value of the 'pt' field */
    public java.lang.Float getPt() {
      return pt;
    }
    
    /** Sets the value of the 'pt' field */
    public baconhep.TTau.Builder setPt(float value) {
      validate(fields()[0], value);
      this.pt = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'pt' field has been set */
    public boolean hasPt() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'pt' field */
    public baconhep.TTau.Builder clearPt() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'eta' field */
    public java.lang.Float getEta() {
      return eta;
    }
    
    /** Sets the value of the 'eta' field */
    public baconhep.TTau.Builder setEta(float value) {
      validate(fields()[1], value);
      this.eta = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'eta' field has been set */
    public boolean hasEta() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'eta' field */
    public baconhep.TTau.Builder clearEta() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'phi' field */
    public java.lang.Float getPhi() {
      return phi;
    }
    
    /** Sets the value of the 'phi' field */
    public baconhep.TTau.Builder setPhi(float value) {
      validate(fields()[2], value);
      this.phi = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'phi' field has been set */
    public boolean hasPhi() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'phi' field */
    public baconhep.TTau.Builder clearPhi() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'm' field */
    public java.lang.Float getM() {
      return m;
    }
    
    /** Sets the value of the 'm' field */
    public baconhep.TTau.Builder setM(float value) {
      validate(fields()[3], value);
      this.m = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'm' field has been set */
    public boolean hasM() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'm' field */
    public baconhep.TTau.Builder clearM() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'e' field */
    public java.lang.Float getE() {
      return e;
    }
    
    /** Sets the value of the 'e' field */
    public baconhep.TTau.Builder setE(float value) {
      validate(fields()[4], value);
      this.e = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'e' field has been set */
    public boolean hasE() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'e' field */
    public baconhep.TTau.Builder clearE() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'q' field */
    public java.lang.Integer getQ() {
      return q;
    }
    
    /** Sets the value of the 'q' field */
    public baconhep.TTau.Builder setQ(int value) {
      validate(fields()[5], value);
      this.q = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'q' field has been set */
    public boolean hasQ() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'q' field */
    public baconhep.TTau.Builder clearQ() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'dzLeadChHad' field */
    public java.lang.Float getDzLeadChHad() {
      return dzLeadChHad;
    }
    
    /** Sets the value of the 'dzLeadChHad' field */
    public baconhep.TTau.Builder setDzLeadChHad(float value) {
      validate(fields()[6], value);
      this.dzLeadChHad = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'dzLeadChHad' field has been set */
    public boolean hasDzLeadChHad() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'dzLeadChHad' field */
    public baconhep.TTau.Builder clearDzLeadChHad() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'nSignalChHad' field */
    public java.lang.Long getNSignalChHad() {
      return nSignalChHad;
    }
    
    /** Sets the value of the 'nSignalChHad' field */
    public baconhep.TTau.Builder setNSignalChHad(long value) {
      validate(fields()[7], value);
      this.nSignalChHad = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'nSignalChHad' field has been set */
    public boolean hasNSignalChHad() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'nSignalChHad' field */
    public baconhep.TTau.Builder clearNSignalChHad() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'nSignalGamma' field */
    public java.lang.Long getNSignalGamma() {
      return nSignalGamma;
    }
    
    /** Sets the value of the 'nSignalGamma' field */
    public baconhep.TTau.Builder setNSignalGamma(long value) {
      validate(fields()[8], value);
      this.nSignalGamma = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'nSignalGamma' field has been set */
    public boolean hasNSignalGamma() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'nSignalGamma' field */
    public baconhep.TTau.Builder clearNSignalGamma() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'antiEleMVA5' field */
    public java.lang.Float getAntiEleMVA5() {
      return antiEleMVA5;
    }
    
    /** Sets the value of the 'antiEleMVA5' field */
    public baconhep.TTau.Builder setAntiEleMVA5(float value) {
      validate(fields()[9], value);
      this.antiEleMVA5 = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'antiEleMVA5' field has been set */
    public boolean hasAntiEleMVA5() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'antiEleMVA5' field */
    public baconhep.TTau.Builder clearAntiEleMVA5() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'antiEleMVA5Cat' field */
    public java.lang.Float getAntiEleMVA5Cat() {
      return antiEleMVA5Cat;
    }
    
    /** Sets the value of the 'antiEleMVA5Cat' field */
    public baconhep.TTau.Builder setAntiEleMVA5Cat(float value) {
      validate(fields()[10], value);
      this.antiEleMVA5Cat = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'antiEleMVA5Cat' field has been set */
    public boolean hasAntiEleMVA5Cat() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'antiEleMVA5Cat' field */
    public baconhep.TTau.Builder clearAntiEleMVA5Cat() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'rawMuonRejection' field */
    public java.lang.Float getRawMuonRejection() {
      return rawMuonRejection;
    }
    
    /** Sets the value of the 'rawMuonRejection' field */
    public baconhep.TTau.Builder setRawMuonRejection(float value) {
      validate(fields()[11], value);
      this.rawMuonRejection = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'rawMuonRejection' field has been set */
    public boolean hasRawMuonRejection() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'rawMuonRejection' field */
    public baconhep.TTau.Builder clearRawMuonRejection() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'rawIso3Hits' field */
    public java.lang.Float getRawIso3Hits() {
      return rawIso3Hits;
    }
    
    /** Sets the value of the 'rawIso3Hits' field */
    public baconhep.TTau.Builder setRawIso3Hits(float value) {
      validate(fields()[12], value);
      this.rawIso3Hits = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'rawIso3Hits' field has been set */
    public boolean hasRawIso3Hits() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'rawIso3Hits' field */
    public baconhep.TTau.Builder clearRawIso3Hits() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'rawIsoMVA3oldDMwoLT' field */
    public java.lang.Float getRawIsoMVA3oldDMwoLT() {
      return rawIsoMVA3oldDMwoLT;
    }
    
    /** Sets the value of the 'rawIsoMVA3oldDMwoLT' field */
    public baconhep.TTau.Builder setRawIsoMVA3oldDMwoLT(float value) {
      validate(fields()[13], value);
      this.rawIsoMVA3oldDMwoLT = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'rawIsoMVA3oldDMwoLT' field has been set */
    public boolean hasRawIsoMVA3oldDMwoLT() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'rawIsoMVA3oldDMwoLT' field */
    public baconhep.TTau.Builder clearRawIsoMVA3oldDMwoLT() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'rawIsoMVA3oldDMwLT' field */
    public java.lang.Float getRawIsoMVA3oldDMwLT() {
      return rawIsoMVA3oldDMwLT;
    }
    
    /** Sets the value of the 'rawIsoMVA3oldDMwLT' field */
    public baconhep.TTau.Builder setRawIsoMVA3oldDMwLT(float value) {
      validate(fields()[14], value);
      this.rawIsoMVA3oldDMwLT = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'rawIsoMVA3oldDMwLT' field has been set */
    public boolean hasRawIsoMVA3oldDMwLT() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'rawIsoMVA3oldDMwLT' field */
    public baconhep.TTau.Builder clearRawIsoMVA3oldDMwLT() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'rawIsoMVA3newDMwoLT' field */
    public java.lang.Float getRawIsoMVA3newDMwoLT() {
      return rawIsoMVA3newDMwoLT;
    }
    
    /** Sets the value of the 'rawIsoMVA3newDMwoLT' field */
    public baconhep.TTau.Builder setRawIsoMVA3newDMwoLT(float value) {
      validate(fields()[15], value);
      this.rawIsoMVA3newDMwoLT = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'rawIsoMVA3newDMwoLT' field has been set */
    public boolean hasRawIsoMVA3newDMwoLT() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'rawIsoMVA3newDMwoLT' field */
    public baconhep.TTau.Builder clearRawIsoMVA3newDMwoLT() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'rawIsoMVA3newDMwLT' field */
    public java.lang.Float getRawIsoMVA3newDMwLT() {
      return rawIsoMVA3newDMwLT;
    }
    
    /** Sets the value of the 'rawIsoMVA3newDMwLT' field */
    public baconhep.TTau.Builder setRawIsoMVA3newDMwLT(float value) {
      validate(fields()[16], value);
      this.rawIsoMVA3newDMwLT = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'rawIsoMVA3newDMwLT' field has been set */
    public boolean hasRawIsoMVA3newDMwLT() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'rawIsoMVA3newDMwLT' field */
    public baconhep.TTau.Builder clearRawIsoMVA3newDMwLT() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'puppiChHadIso' field */
    public java.lang.Float getPuppiChHadIso() {
      return puppiChHadIso;
    }
    
    /** Sets the value of the 'puppiChHadIso' field */
    public baconhep.TTau.Builder setPuppiChHadIso(float value) {
      validate(fields()[17], value);
      this.puppiChHadIso = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'puppiChHadIso' field has been set */
    public boolean hasPuppiChHadIso() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'puppiChHadIso' field */
    public baconhep.TTau.Builder clearPuppiChHadIso() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'puppiGammaIso' field */
    public java.lang.Float getPuppiGammaIso() {
      return puppiGammaIso;
    }
    
    /** Sets the value of the 'puppiGammaIso' field */
    public baconhep.TTau.Builder setPuppiGammaIso(float value) {
      validate(fields()[18], value);
      this.puppiGammaIso = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'puppiGammaIso' field has been set */
    public boolean hasPuppiGammaIso() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'puppiGammaIso' field */
    public baconhep.TTau.Builder clearPuppiGammaIso() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'puppiNeuHadIso' field */
    public java.lang.Float getPuppiNeuHadIso() {
      return puppiNeuHadIso;
    }
    
    /** Sets the value of the 'puppiNeuHadIso' field */
    public baconhep.TTau.Builder setPuppiNeuHadIso(float value) {
      validate(fields()[19], value);
      this.puppiNeuHadIso = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'puppiNeuHadIso' field has been set */
    public boolean hasPuppiNeuHadIso() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'puppiNeuHadIso' field */
    public baconhep.TTau.Builder clearPuppiNeuHadIso() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'puppiChHadIsoNoLep' field */
    public java.lang.Float getPuppiChHadIsoNoLep() {
      return puppiChHadIsoNoLep;
    }
    
    /** Sets the value of the 'puppiChHadIsoNoLep' field */
    public baconhep.TTau.Builder setPuppiChHadIsoNoLep(float value) {
      validate(fields()[20], value);
      this.puppiChHadIsoNoLep = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'puppiChHadIsoNoLep' field has been set */
    public boolean hasPuppiChHadIsoNoLep() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'puppiChHadIsoNoLep' field */
    public baconhep.TTau.Builder clearPuppiChHadIsoNoLep() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'puppiGammaIsoNoLep' field */
    public java.lang.Float getPuppiGammaIsoNoLep() {
      return puppiGammaIsoNoLep;
    }
    
    /** Sets the value of the 'puppiGammaIsoNoLep' field */
    public baconhep.TTau.Builder setPuppiGammaIsoNoLep(float value) {
      validate(fields()[21], value);
      this.puppiGammaIsoNoLep = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'puppiGammaIsoNoLep' field has been set */
    public boolean hasPuppiGammaIsoNoLep() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'puppiGammaIsoNoLep' field */
    public baconhep.TTau.Builder clearPuppiGammaIsoNoLep() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'puppiNeuHadIsoNoLep' field */
    public java.lang.Float getPuppiNeuHadIsoNoLep() {
      return puppiNeuHadIsoNoLep;
    }
    
    /** Sets the value of the 'puppiNeuHadIsoNoLep' field */
    public baconhep.TTau.Builder setPuppiNeuHadIsoNoLep(float value) {
      validate(fields()[22], value);
      this.puppiNeuHadIsoNoLep = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'puppiNeuHadIsoNoLep' field has been set */
    public boolean hasPuppiNeuHadIsoNoLep() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'puppiNeuHadIsoNoLep' field */
    public baconhep.TTau.Builder clearPuppiNeuHadIsoNoLep() {
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'hpsDisc' field */
    public java.lang.Double getHpsDisc() {
      return hpsDisc;
    }
    
    /** Sets the value of the 'hpsDisc' field */
    public baconhep.TTau.Builder setHpsDisc(double value) {
      validate(fields()[23], value);
      this.hpsDisc = value;
      fieldSetFlags()[23] = true;
      return this; 
    }
    
    /** Checks whether the 'hpsDisc' field has been set */
    public boolean hasHpsDisc() {
      return fieldSetFlags()[23];
    }
    
    /** Clears the value of the 'hpsDisc' field */
    public baconhep.TTau.Builder clearHpsDisc() {
      fieldSetFlags()[23] = false;
      return this;
    }

    @Override
    public TTau build() {
      try {
        TTau record = new TTau();
        record.pt = fieldSetFlags()[0] ? this.pt : (java.lang.Float) defaultValue(fields()[0]);
        record.eta = fieldSetFlags()[1] ? this.eta : (java.lang.Float) defaultValue(fields()[1]);
        record.phi = fieldSetFlags()[2] ? this.phi : (java.lang.Float) defaultValue(fields()[2]);
        record.m = fieldSetFlags()[3] ? this.m : (java.lang.Float) defaultValue(fields()[3]);
        record.e = fieldSetFlags()[4] ? this.e : (java.lang.Float) defaultValue(fields()[4]);
        record.q = fieldSetFlags()[5] ? this.q : (java.lang.Integer) defaultValue(fields()[5]);
        record.dzLeadChHad = fieldSetFlags()[6] ? this.dzLeadChHad : (java.lang.Float) defaultValue(fields()[6]);
        record.nSignalChHad = fieldSetFlags()[7] ? this.nSignalChHad : (java.lang.Long) defaultValue(fields()[7]);
        record.nSignalGamma = fieldSetFlags()[8] ? this.nSignalGamma : (java.lang.Long) defaultValue(fields()[8]);
        record.antiEleMVA5 = fieldSetFlags()[9] ? this.antiEleMVA5 : (java.lang.Float) defaultValue(fields()[9]);
        record.antiEleMVA5Cat = fieldSetFlags()[10] ? this.antiEleMVA5Cat : (java.lang.Float) defaultValue(fields()[10]);
        record.rawMuonRejection = fieldSetFlags()[11] ? this.rawMuonRejection : (java.lang.Float) defaultValue(fields()[11]);
        record.rawIso3Hits = fieldSetFlags()[12] ? this.rawIso3Hits : (java.lang.Float) defaultValue(fields()[12]);
        record.rawIsoMVA3oldDMwoLT = fieldSetFlags()[13] ? this.rawIsoMVA3oldDMwoLT : (java.lang.Float) defaultValue(fields()[13]);
        record.rawIsoMVA3oldDMwLT = fieldSetFlags()[14] ? this.rawIsoMVA3oldDMwLT : (java.lang.Float) defaultValue(fields()[14]);
        record.rawIsoMVA3newDMwoLT = fieldSetFlags()[15] ? this.rawIsoMVA3newDMwoLT : (java.lang.Float) defaultValue(fields()[15]);
        record.rawIsoMVA3newDMwLT = fieldSetFlags()[16] ? this.rawIsoMVA3newDMwLT : (java.lang.Float) defaultValue(fields()[16]);
        record.puppiChHadIso = fieldSetFlags()[17] ? this.puppiChHadIso : (java.lang.Float) defaultValue(fields()[17]);
        record.puppiGammaIso = fieldSetFlags()[18] ? this.puppiGammaIso : (java.lang.Float) defaultValue(fields()[18]);
        record.puppiNeuHadIso = fieldSetFlags()[19] ? this.puppiNeuHadIso : (java.lang.Float) defaultValue(fields()[19]);
        record.puppiChHadIsoNoLep = fieldSetFlags()[20] ? this.puppiChHadIsoNoLep : (java.lang.Float) defaultValue(fields()[20]);
        record.puppiGammaIsoNoLep = fieldSetFlags()[21] ? this.puppiGammaIsoNoLep : (java.lang.Float) defaultValue(fields()[21]);
        record.puppiNeuHadIsoNoLep = fieldSetFlags()[22] ? this.puppiNeuHadIsoNoLep : (java.lang.Float) defaultValue(fields()[22]);
        record.hpsDisc = fieldSetFlags()[23] ? this.hpsDisc : (java.lang.Double) defaultValue(fields()[23]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
